import {
  BarChart3,
  Box,
  Home,
  LogOut,
  Package,
  ShoppingCart,
  Tag,
  Truck,
  Users,
  UserCog,
  Warehouse,
  RefreshCw,
  ShoppingBag,
} from "lucide-react";

export const navigation = [
  { name: "Dashboard", href: "dashboard", icon: Home, role: ["manager"] },
  {
    name: "Dashboard",
    href: "cashier-dashboard",
    icon: Home,
    role: ["cashier"],
  },
  { name: "POS", href: "pos", icon: ShoppingBag, role: ["manager", "cashier"] },
  {
    name: "Products",
    href: "products",
    icon: Package,
    role: ["manager", "stocker", "cashier"],
  },
  { name: "Sales", href: "sales", icon: ShoppingCart, role: ["manager"] },
  {
    name: "Inventory",
    href: "inventory",
    icon: Box,
    role: ["manager", "stocker"],
  },
  {
    name: "Customers",
    href: "customers",
    icon: Users,
    role: ["manager", "cashier"],
  },
  {
    name: "Purchases",
    href: "purchases",
    icon: Warehouse,
    role: ["manager", "stocker"],
  },
  {
    name: "Suppliers",
    href: "suppliers",
    icon: Truck,
    role: ["manager", "stocker"],
  },
  { name: "Employees", href: "employees", icon: UserCog, role: ["manager"] },
  { name: "Reports", href: "reports", icon: BarChart3, role: ["manager"] },
  {
    name: "Returns",
    href: "returns",
    icon: RefreshCw,
    role: ["manager", "stocker"],
  },
];
